name: App Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setting up PHP
        uses: ./.github/actions/php

      - name: Installing Composer
        uses: ./.github/actions/composer

      - name: Running PHPStan
        uses: ./.github/actions/phpstan

      - name: Running PHPInsights
        uses: ./.github/actions/phpinsights

      - name: Running PHPCS
        run: ./vendor/bin/phpcs

      - name: Running PHPUnit
        run: ./vendor/bin/phpunit
